# Create a cohort calendar

1. Verify that cohort_calendar.py has the cohort entry with start and stop dates. 
1. Verify student_experience/professional_development dates are added to the cohort_calendar.py function create_sepd_days(). Contact student experience for future dates. ***NOTE*** SE/PD days are no longer applicable BUT the function to create the calendar requires 2 SE/PD days in order to operate. cohort_calendar.py will need to be refactored but a quick work around is to schedule the SE/PD days during capstone/weekend and then just rename the days before it is saved. ***NOTE***
2. If you run into issues, check with the function "shift_capstones()"
3. This program will write a csv with events (lessons and holidays) and dates. 
4. The final step is to create that calendar, "<cohort_name> (instructors)", in google calendar and import the csv to the new calendar. Be sure and share the calendar with the team.

In [1]:
import pandas as pd
import cohort_calendar
cohort_name = 'somerville'
new_cohort_calendar = cohort_calendar.get_new_cohort_calendar(cohort_name,
                                                              generic_lessons_filepath='generic_lessons_days_full_wednesdays.csv',
                                                              holidays_file_path = 'student_holidays.csv', 
                                                              se_pd_days_path = 'se_pd_days.csv')

In [2]:
new_cohort_calendar.head(25)

                                              Subject Start Date
0                    welcome L00  welcome day [instr] 2023-06-13
1                 welcome L01 syllabus review [instr] 2023-06-13
2       fundamentals L00 what is data science [instr] 2023-06-14
3   fundamentals L01 explore through hyperdoc [instr] 2023-06-14
4      fundamentals L02 data science pipeline [instr] 2023-06-15
5      fundamentals L04 review for assessment [instr] 2023-06-15
6                 fundamentals L04 assessment [instr] 2023-06-16
7          fundamentals L04 assessment review [instr] 2023-06-16
8            fundamentals L05 project kickoff [instr] 2023-06-16
9                                             Weekend 2023-06-17
10                                            Weekend 2023-06-18
11                                         Juneteenth 2023-06-19
12     fundamentals L05 project presentations [instr] 2023-06-20
13        [task] generate mySQL student users [instr] 2023-06-21
14                            CLI/GIT L00 cli [instr] 2023-06-21
15                                    Q2 Dept Offsite 2023-06-22
16                                   H1 All Staff Day 2023-06-23
17                                            Weekend 2023-06-24
18                                            Weekend 2023-06-25
19                            CLI/GIT L01 git [instr] 2023-06-26
20                           SQL L00 overview [instr] 2023-06-27
21                       SQL L01 dbs & tables [instr] 2023-06-27
22                   SQL L02 basic statements [instr] 2023-06-27
23            SQL L02 basic statements review [instr] 2023-06-27
24                            SQL L03 clauses [instr] 2023-06-27

In [3]:
new_cohort_calendar.tail(25)

                                   Subject Start Date
240                advanced topics [instr] 2023-10-20
241                                Weekend 2023-10-21
242                                Weekend 2023-10-22
243  capstone L01 capstone kickoff [instr] 2023-10-23
244     capstone L02 capstone work [instr] 2023-10-24
245     capstone L03 capstone work [instr] 2023-10-25
246     capstone L04 capstone work [instr] 2023-10-26
247                       H2 All Staff Day 2023-10-27
248                                Weekend 2023-10-28
249                                Weekend 2023-10-29
250     capstone L05 capstone work [instr] 2023-10-30
251     capstone L06 capstone work [instr] 2023-10-31
252     capstone L07 capstone work [instr] 2023-11-01
253     capstone L08 capstone work [instr] 2023-11-02
254     capstone L09 capstone work [instr] 2023-11-03
255                                Weekend 2023-11-04
256                                Weekend 2023-11-05
257     capstone L10 capstone work [instr] 2023-11-06
258     capstone L11 capstone work [instr] 2023-11-07
259    capstone L12 review panel I [instr] 2023-11-08
260   capstone L13 review panel II [instr] 2023-11-09
261                Veteran's Day (Holiday) 2023-11-10
262                                Weekend 2023-11-11
263                                Weekend 2023-11-12
264                              SE/PD Day 2023-11-13

In [4]:
new_cohort_calendar.loc[264, 'Subject'] = 'Graduation'

In [5]:
new_cohort_calendar.tail()

                                  Subject Start Date
260  capstone L13 review panel II [instr] 2023-11-09
261               Veteran's Day (Holiday) 2023-11-10
262                               Weekend 2023-11-11
263                               Weekend 2023-11-12
264                            Graduation 2023-11-13

In [6]:
csv_name = cohort_name+'_cal.csv'
new_cohort_calendar.to_csv(csv_name)